import Vue from 'vue'
import { Button, Grid, GridItem, Tabbar, TabbarItem, NavBar, Swipe, SwipeItem, Toast, Loading, Tabs, Tab, Sticky, Icon, List } from 'vant';
Vue.use(Button)
Vue.use(Grid)
Vue.use(Tabbar)
Vue.use(TabbarItem)
Vue.use(NavBar)
Vue.use(Swipe)
Vue.use(SwipeItem)
Vue.use(Toast)
Vue.use(Loading)
Vue.use(GridItem)
Vue.use(Tabs)
Vue.use(Tab)
Vue.use(Sticky)
Vue.use(Icon)
Vue.use(List)
